### ISSUE TITLE
Debounce en el cambio de precio

### ISSUE THREAD

**Issue by alejoasotelo** [amendez/cakecalc#1]
Hola @amendez primero que nada decirte que está bárbaro el proyecto, conectas la wallet y sale andando, golazo!!!

Creé el issue para proponer agregar en el cambio de precio "debounce". Por qué? Porque si intento cambiar el precio, por cada número que cambio recalcula los gráficos y consume recursos, con un debounce se calcularía solo una vez, en vez de en cada cambio de número y se optimizaría bastante para pcs o celulares con pocos recursos.

Abrazo!

**Comment by amendez** [comment]
Hola Alejo, gracias por el feedback! Agregué el debounce en este commit: https://github.com/amendez/cakecalc/commit/3bd5417314a591b4c409761596f1e64473c540aa

Lo puse en 1 segundo de tiempo, puede ser un poco alto, pero como bien decis, prefiero que funcione lo mejor posible desde la mayor cantidad de dispositivos.

Nunca había usado debounce en Quasar, y la verdad que fue muuy fácil de usar.

Gracias! Abrazo
